### ISSUE TITLE
Too many options in Azure build sample step

### ISSUE THREAD

**Issue by josvazg** [OddBloke/ubuntu-standalone-builder#1]
The sample azure command to build the image in Azure leaves too many questions to be answered by the user:

```
$ azure vm quick-create     --custom-data build-config.yaml     --image-urn canonical:ubuntuserver:16.04-LTS:latest
info:    Executing command vm quick-create
Resource group name:  josvaz
Virtual machine name:  build-test
Location name:  northeurope
Operating system Type [Windows, Linux]:  Linux
User name:  ubuntu
Password: **********
Confirm password: **********
```

Many of those could be trimmed out:

- Operating system MUST be Linux
- User name cloud be ubuntu
- Resource group could be a default name? image-builder?

The command could be something like this instead:

`azure vm quick-create --custom-data build-config.yaml --image-urn canonical:ubuntuserver:16.04-LTS:latest --admin-username ubuntu --os-type Linux --resource-group ubuntu-image-builder`

**Comment by OddBloke** [comment]
I think the resource group that people want to use will be quite specific to individuals, so I'm not going to include that. Adding the other two now.
