### ISSUE TITLE
Builder disk requirements

### ISSUE THREAD

**Issue by rcj4747** [OddBloke/ubuntu-standalone-builder#3]
Running this builder on AWS HVM EBS(ssd) instance
with the default 8GB disk results in build failure
due to disk space exhaustion.  The disk space
requirements should be documented in README.md.
Additionally, if additional cloud examples are
provided it will require an AWS example to
show how to override the disk configuration.

**Comment by OddBloke** [comment]
I've pushed a commit which will handle this, but I need to verify that the disk size I specified is actually of an appropriate size before I propose it for merging.
